services:
  backend:
    build:
      dockerfile: Dockerfile
    # command: python manage.py runsslserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - db_data:/app/db_data
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    logging:
      driver: json-file
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/mysql:/var/lib/mysql
      - ./db_data/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./db_data/dump/:/var/dump/
      - ./db_data/initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo

volumes:
  db_data:

